# Generated by Django 4.1.4 on 2022-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(blank=True, max_length=1, null=True)),
                ('model', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
    ]
